app/models.py
from app import db,login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

class Permission:
	FOLLOW = 0X01
	COMMENT = 0X02
	WRITE_ARTICLES = 0X4
	MODERATE_COMMENTS = 0X08
	ADMINISTER = 0X80
	

class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	body = db.Column(db.Text)
	timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
	author_id = db.Column(db.Integer, db.ForeignKey('user.id'))
	
class User(UserMixin,db.Model):
	def __init__(self,**kwargs):
		super(User,self).__init__(**kwargs)
		if self.role is None:
			self.role = Role.query.filter_by(default=True).first()
	
	id = db.Column(db.Integer,primary_key=True)
	email = db.Column(db.String(64),unique=True,index=True)
	username = db.Column(db.String(64),unique=True, index=True)
	role_id = db.Column(db.Integer,db.ForeignKey('role.id'))
	role = db.relationship('Role',backref=db.backref('Users',lazy=True))
	password_hash = db.Column(db.String(128))
	posts = db.relationship('Post',backref=db.backref('author',lazy=True))
	
	def can(self, perm):
		return self.role is not None and self.role.has_permission(perm)
	
	@property
	def password(self):
		raise AttributeError('password is not a readable attribute')
	
	@password.setter
	def password(self,password):
		self.password_hash = generate_password_hash(password)
		
	def verify_password(self,password):
		return check_password_hash(self.password_hash, password)
	
	def __repr__(self):
		return '<User %r>' % self.username

class Role(db.Model):
	id = db.Column(db.Integer,primary_key=True)
	name = db.Column(db.String(64),unique=True)
	permissions = db.Column(db.Integer)
	default = db.Column(db.Boolean,default=False,index=True)
	#users = db.relationship('User',backref='role')
	
	def has_permission(self, perm):
		return self.permissions & perm == perm
	
	@staticmethod
	def remove_roles(*args):
		name = args
		print(args)
		print(len(args))
		for r in args:
			role = Role.query.filter_by(name=r).first()
			if role is not None:
				db.session.delete(role)
				print('Success to delete role %s in Role table.'% r)
			else:
				print('Role name %s is not exist in Role table.'% r)
				
		if len(args) is 0:
			print('Delete all roles in Role table.')
			for r in Role.query.all():
				db.session.delete(r)
				
		db.session.commit()
			
	
	@staticmethod
	def insert_roles():
		roles = {
			'User':(Permission.FOLLOW|
					Permission.COMMENT|
					Permission.WRITE_ARTICLES, True),
			'Administrator':(0xff,False)
			}
		for r in roles:
			role = Role.query.filter_by(name=r).first()
			if role is None:
				role = Role(name=r)
			role.permissions=roles[r][0]
			role.default=roles[r][1]
			db.session.add(role)
		db.session.commit()
	
	def __repr__(self):
		return '<Role %r>' % self.name

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import Required

class NameForm(Form):
	name = StringField('猜猜我的名字？',validators=[Required()])
	submit = SubmitField('提交')
	
class PostForm(Form):
	body = TextAreaField('你想说说什么？',validators=[Required()])
	submit = SubmitField('提交')
	

app/__init__.py
from flask import Flask,render_template
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from .config import config

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)
	
	migrate = Migrate(app, db)
	
	bootstrap.init_app(app)
	moment.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)
	
	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)
	
	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint, url_prefix='/auth')
	
	from .game import game as game_blueprint
	app.register_blueprint(game_blueprint, url_prefix='/game')

	
	return app

app/game/__init__.py
from flask import Blueprint

game = Blueprint('game',__name__)

from . import views

app/game/views.py
from flask import render_template,redirect,url_for,flash
from . import game

@game.route('/box',methods=['GET'])
def box():
	return render_template('game/box/index.html')
	
	

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors
from ..models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
from . import main
from .. import db
from datetime import datetime
from flask import render_template,session,redirect,url_for
from flask_login import current_user
from .forms import NameForm,PostForm
from ..models import User,Post,Permission
		
@main.route('/', methods=['GET','POST'])
def index():
	form = PostForm()
	if current_user.can(Permission.WRITE_ARTICLES) and\
			form.validate_on_submit():
		post = Post(body=form.body.data,
					author=current_user._get_current_object())
		db.session.add(post)
		return redirect(url_for('main.index'))
	posts = Post.query.order_by(Post.timestamp.desc()).all()
	return render_template('index.html',
		form = form, posts = posts)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Yococo (๑•̀ㅂ•́)و✧{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">朱清的网站</a>
        </div>
        <div class="navbar-collapse collapse">
			{% if current_user.is_authenticated %}
			<ul class="nav navbar-nav">
                <li><a href="/">笔记</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="/">传送门</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{url_for('game.box')}}">小游戏</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{url_for('auth.manage')}}">管理</a></li>
            </ul>
			{% endif %}			
            <ul class="nav navbar-nav navbar-right">
				{% if current_user.is_authenticated %}
                <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
				{% else %}
                <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
				{% endif %}
            </ul>				
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.lang('zh-CN') }}
{% endblock %}

app/templates/game/box/index.html
{% extends "base.html" %}


{% block content %}
<style>
.exp1{font-size:15px;} 
.game{
	width:560px;
	margin:5px auto;
}
.title{
	width:800px;

}
</style>
<body onkeydown="doKeyDown(event)"><!--身体-->
	<div class="game exp1">
		<div id="msg" ></div>
		<canvas id="canvas" width="560" height="560"></canvas>
		<input type="button" value="上一关" onClick="NextLevel(-1)">
		<input type="button" value="下一关" onClick="NextLevel(1)">
		<input type="button" value="重玩本关" onClick="NextLevel(0)">
		<input type="button" value="游戏说明" onClick="showHelp()">
	</div>

<link id="block" href="{{ url_for('static',_external=True,filename='game/box/images/block.gif') }}"></link>
<link id="wall" href="{{ url_for('static',_external=True,filename='game/box/images/wall.png') }}"></link>
<link id="box" href="{{ url_for('static',_external=True,filename='game/box/images/box.png') }}"></link>
<link id="ball" href="{{ url_for('static',_external=True,filename='game/box/images/ball.png') }}"></link>
<link id="up" href="{{ url_for('static',_external=True,filename='game/box/images/up.png') }}"></link>
<link id="down" href="{{ url_for('static',_external=True,filename='game/box/images/down.png') }}"></link>
<link id="left" href="{{ url_for('static',_external=True,filename='game/box/images/left.png') }}"></link>
<link id="right" href="{{ url_for('static',_external=True,filename='game/box/images/right.png') }}"></link>
</body>	
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static',_external=True,filename='game/box/js/mapdata100.js') }}"></script>
<script>
	var can = document.getElementById("canvas");
	var msg = document.getElementById("msg");
	var cxt = can.getContext("2d");
	var w = 35,h = 35;
	var curMap;//当前的地图
	var curLevel;//当前等级的地图
	var curMan;//初始化小人
	var iCurlevel = 0;//关卡数
	var moveTimes = 0;//移动了多少次
	//预加载所有图片
	var oImgs = {
		"block" : document.getElementById("block").href,
		"wall" : document.getElementById("wall").href,
		"box" : document.getElementById("box").href,
		"ball" : document.getElementById("ball").href,
		"up" : document.getElementById("up").href,
		"down" : document.getElementById("down").href,
		"left" : document.getElementById("left").href,
		"right" : document.getElementById("right").href,
	}
	function imgPreload(srcs,callback){
		var count = 0,imgNum = 0,images = {};

		for(src in srcs){
			imgNum++;
		}
		for(src in srcs ){
			images[src] = new Image();
			images[src].onload = function(){
				//判断是否所有的图片都预加载完成
				if (++count >= imgNum)
				{
					callback(images);
				}
			}
			images[src].src = srcs[src];
		}
	}
	var block,wall,box,ball,up,down,left,right;
	imgPreload(oImgs,function(images){
		console.log(images.block);
		block = images.block;
		wall = images.wall;
		box = images.box;
		ball = images.ball;
		up = images.up;
		down = images.down;
		left = images.left;
		right = images.right;
		init();
	});
	//初始化游戏
	function init(){
		//InitMap();
		//DrawMap(levels[0]);
		initLevel();//初始化对应等级的游戏
		showMoveInfo();//初始化对应等级的游戏数据
	}
	//绘制地板
	function InitMap(){
		for (var i=0;i<16 ;i++ )
		{
			for (var j=0;j<16 ;j++ )
			{
				cxt.drawImage(block,w*j,h*i,w,h);
			}
		}
	}
	//小人位置坐标
	function Point(x,y){
		this.x = x;
		this.y = y;
	}
	var perPosition = new Point(5,5);//小人的初始标值
	//绘制每个游戏关卡地图
	function DrawMap(level){
		for (var i=0;i<level.length ;i++ )
		{
			for (var j=0;j<level[i].length ;j++ )
			{
				var pic = block;//初始图片
				switch (level[i][j])
				{
				case 1://绘制墙壁
					pic = wall;
					break;
				case 2://绘制陷进
					pic = ball;
					break;
				case 3://绘制箱子
					pic = box;
					break;
				case 4://绘制小人
					pic = curMan;//小人有四个方向 具体显示哪个图片需要和上下左右方位值关联
					//获取小人的坐标位置
					perPosition.x = i;
					perPosition.y = j;
					break;
				case 5://绘制箱子及陷进位置
					pic = box;
					break;
				}
				//每个图片不一样宽 需要在对应地板的中心绘制地图
				cxt.drawImage(pic,w*j-(pic.width-w)/2,h*i-(pic.height-h),pic.width,pic.height)
			}
		}
	}
	//初始化游戏等级
	function initLevel(){
		curMap = copyArray(levels[iCurlevel]);//当前移动过的游戏地图
		curLevel = levels[iCurlevel];//当前等级的初始地图
		curMan = down;//初始化小人
		InitMap();//初始化地板
		DrawMap(curMap);//绘制出当前等级的地图
	}
	//下一关
	function NextLevel(i){
		//iCurlevel当前的地图关数
		iCurlevel = iCurlevel + i;
		if (iCurlevel<0)
		{
			iCurlevel = 0;
			return;
		}
		var len = levels.length;
		if (iCurlevel > len-1)
		{
			iCurlevel = len-1;
		}
		initLevel();//初始当前等级关卡
		moveTimes = 0;//游戏关卡移动步数清零
		showMoveInfo();//初始化当前关卡数据
	}
	//小人移动
	function go(dir){
		var p1,p2;
		switch (dir)
		{
		case "up":
			curMan = up;
			//获取小人前面的两个坐标位置来进行判断小人是否能够移动
			p1 = new Point(perPosition.x-1,perPosition.y);
			p2 = new Point(perPosition.x-2,perPosition.y);
			break;
		case "down":
			curMan = down;
			p1 = new Point(perPosition.x+1,perPosition.y);
			p2 = new Point(perPosition.x+2,perPosition.y);
			break;
		case "left":
			curMan = left;
			p1 = new Point(perPosition.x,perPosition.y-1);
			p2 = new Point(perPosition.x,perPosition.y-2);
			break;
		case "right":
			curMan = right;
			p1 = new Point(perPosition.x,perPosition.y+1);
			p2 = new Point(perPosition.x,perPosition.y+2);
			break;
		}
		//若果小人能够移动的话，更新游戏数据，并重绘地图
		if (Trygo(p1,p2))
		{
			moveTimes ++;
			showMoveInfo();
		}
		//重绘地板
		InitMap();
		//重绘当前更新了数据的地图
		DrawMap(curMap);
		//若果移动完成了进入下一关
		if (checkFinish())
		{
			alert("恭喜过关！！");
			NextLevel(1);
		}
	}
	//判断是否推成功
	function checkFinish(){
		for (var i=0;i<curMap.length ;i++ )
		{
			for (var j=0;j<curMap[i].length ;j++ )
			{
				//当前移动过的地图和初始地图进行比较，若果初始地图上的陷进参数在移动之后不是箱子的话就指代没推成功
				if (curLevel[i][j] == 2 && curMap[i][j] != 3 || curLevel[i][j] == 5 && curMap[i][j] != 3)
				{
					return false;
				}
			}
		}
		return true;
	}
	//判断小人是否能够移动
	function Trygo(p1,p2){
		if(p1.x<0) return false;//若果超出地图的上边，不通过
		if(p1.y<0) return false;//若果超出地图的左边，不通过
		if(p1.x>curMap.length) return false;//若果超出地图的下边，不通过
		if(p1.y>curMap[0].length) return false;//若果超出地图的右边，不通过
		if(curMap[p1.x][p1.y]==1) return false;//若果前面是墙，不通过
		if (curMap[p1.x][p1.y]==3 || curMap[p1.x][p1.y]==5)
		{//若果小人前面是箱子那就还需要判断箱子前面有没有障碍物(箱子/墙)
			if (curMap[p2.x][p2.y]==1 || curMap[p2.x][p2.y]==3)
			{
				return false;
			}
			//若果判断不成功小人前面的箱子前进一步
			curMap[p2.x][p2.y] = 3;//更改地图对应坐标点的值
			//console.log(curMap[p2.x][p2.y]);
		}
		//若果都没判断成功小人前进一步
		curMap[p1.x][p1.y] = 4;//更改地图对应坐标点的值
		//若果小人前进了一步，小人原来的位置如何显示
		var v = curLevel[perPosition.x][perPosition.y];
		if (v!=2)//若果刚开始小人位置不是陷进的话
		{
			if (v==5)//可能是5 既有箱子又陷进
			{
				v=2;//若果小人本身就在陷进里面的话移开之后还是显示陷进
			}else{
				v=0;//小人移开之后之前小人的位置改为地板
			}
		}
		//重置小人位置的地图参数
		curMap[perPosition.x][perPosition.y] = v;
		//若果判断小人前进了一步，更新坐标值
		perPosition = p1;
		//若果小动了 返回true 指代能够移动小人
		return true;
	}
	//判断是否推成功
	//与键盘上的上下左右键关联
	function doKeyDown(event){
		switch (event.keyCode)
		{
		case 37://左键头
			go("left");
			break;
		case 38://上键头
			go("up");
			break;
		case 39://右箭头
			go("right");
			break;
		case 40://下箭头
			go("down");
			break;
		}

	}
	//完善关卡数据及游戏说明
	function showMoveInfo(){
		msg.innerHTML = "第" + (iCurlevel+1) +"关 移动次数: "+ moveTimes;
	}
	//游戏说明
	var showhelp = false;
	function showHelp(){
		showhelp = !showhelp;
		if (showhelp)
		{
			msg.innerHTML = "用键盘上的上、下、左、右键移动小人，把箱子全部推到小球的位置即可过关。箱子只可向前推，不能往后拉，并且小人一次只能推动一个箱子。";
		}else{
			showMoveInfo();
		}
	}

	//克隆二维数组
	function copyArray(arr){
		var b=[];//每次移动更新地图数据都先清空再添加新的地图
		for (var i=0;i<arr.length ;i++ )
		{
			b[i] = arr[i].concat();//链接两个数组
		}
		return b;
	}
</script>
{% endblock %}

<!--
</body>	
</html>
-->

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="page-header">
    <h1>你好, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}陌生人{% endif %}!</h1>
</div>
<div>
	{% if current_user.can(Permission.WRITE_ARTICLES) %}
	{{ wtf.quick_form(form) }}
	{% endif %}
</div>

<ul class="post">
	{% for post in posts%}
	<li class="post">
		<div class="profile-thumbnail">
		</div>
		<div class="post-content">
		<div class="post-date">
			{{ moment(post.timestamp).fromNow() }}
		</div>
		<div class="post-author">
			<a>
			{{ post.author.username }}
			</a>		
		</div>
		<div class="post-body">
			{{ post.body }}
		</div>
		</div>
	</li>
	{% endfor %}
</ul>
{% endblock %}